language: ruby
rvm:
 - jruby-9.4
 - jruby-9.3
 - jruby-9.2
 - 3.1
 - 3.0
 - 2.7
 - 2.6
gemfile:
  - gemfiles/rails60.gemfile
  - gemfiles/rails61.gemfile
sudo: false
cache: bundler
notifications:
  email:
    on_success: never
    on_failure: always
